# Generated by Django 5.0.3 on 2026-10-07 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Должность')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('sphere', models.CharField(db_index=True, max_length=255, verbose_name='Сфера деятельности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('work_format', models.CharField(choices=[('remote', 'Удаленно'), ('office', 'Очно'), ('hybrid', 'Гибрид')], max_length=20, verbose_name='Формат работы')),
                ('salary_from', models.IntegerField(blank=True, null=True, verbose_name='ЗП от')),
                ('salary_to', models.IntegerField(blank=True, null=True, verbose_name='ЗП до')),
                ('source', models.CharField(max_length=50, verbose_name='Источник (HH, Habr, TG)')),
                ('external_url', models.URLField(unique=True, verbose_name='Ссылка на вакансию')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'unique_together': {('user', 'vacancy')},
            },
        ),
    ]
